cabal-version: 3.0

name:                conduit-example
version:             0.1.0.0
license:             BSD-3-Clause
build-type:          Simple

executable conduit-example
  main-is:            Main.hs
  hs-source-dirs:     src 

  default-language:   GHC2024

  build-depends:
      base
    , conduit

  ghc-options:
      -Wall
      -Wcompat
      -Widentities
      -Wincomplete-record-updates
      -Wincomplete-uni-patterns
      -Wmissing-export-lists
      -Wmissing-home-modules
      -Wpartial-fields
      -Wredundant-constraints

  default-extensions:
      OverloadedStrings